name: Update GCE instance container

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag for docker image"
        required: true 


jobs:
  update-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.SA_key }}
        project_id: ${{ secrets.PROJECT_ID }}  

    - name: Setup gcloud CLI
      uses: 'google-github-actions/setup-gcloud@v1'
      

    - name: Update Container on GCE instance
      run: |
        gcloud compute instances update-container nodeapp-docker \
          --zone us-east1-b \
          --container-image gcr.io/${{ secrets.PROJECT_ID }}/nodeapp:${{ github.event.inputs.tag }}  